---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-master
  template:
    metadata:
      labels:
        app: hadoop-master
    spec:
      containers:
        - name: hadoop-master
          image: apache/hadoop:3
          ports:
            - containerPort: 9000
          command: ["/bin/bash", "-c"]
          args:
            - hdfs namenode -format && start-dfs.sh && start-yarn.sh && tail -f /dev/null
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-master
spec:
  type: LoadBalancer
  selector:
    app: hadoop-master
  ports:
    - port: 9000
      targetPort: 9000