apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: kel4/14848-project-jenkins-x86:0.0.3
          imagePullPolicy: Always
          name: jenkins
          ports:
            - containerPort: 8080