node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    environment {
      scannerHome = tool 'sonar-scanner-default';
    }
    steps {
      withSonarQubeEnv('sq-server') {
        sh "${scannerHome}/bin/sonar-scanner"
        }
    }
  }
}