pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarScanner'
                    withSonarQubeEnv('SonarQube') {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }

        stage('Deploy to Hadoop') {
            when {
                expression {
                    currentBuild.resultIsBetterOrEqualTo('SUCCESS')
                }
            }
            steps {
                script {
                    sh '''
                        kubectl cp src/hadoop-job hadoop-master-pod:/tmp/
                        kubectl exec hadoop-master-pod -- /bin/bash -c "hadoop jar /opt/hadoop/share/hadoop/tools/lib/hadoop-streaming-*.jar \
                            -files /tmp/hadoop-job/mapper.py,/tmp/hadoop-job/reducer.py \
                            -mapper /tmp/hadoop-job/mapper.py \
                            -reducer /tmp/hadoop-job/reducer.py \
                            -input /input/data \
                            -output /output/result"
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}